# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6771e5e9110c4761bbce517b280a1456950247f12440e37f0a14fed9d6366f4305322f4114be84c4fae5f7e61d5d9721b55e900478c70ccfa08c8767c92fb3b

test:
  secret_key_base: dd47316d3af0f4037397e7b3909605fdc379e472dc2e33349c8786238acc998a3697c178edf62244ed9ba1fdaad0634a6e67d10de65b0e64fe323f253d806a00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
